---
- hosts: media
  tasks:

  vars_files:
    - vars/main.yaml

- name: Group by Distribution
  hosts: all
  tasks:
    - group_by: key=${ansible_distribution}

- name: Set Time Zone
  hosts: Ubuntu
  gather_facts: False
  tasks:
    - name: Set timezone variables
      copy: content='Atlantic/Reykjavik'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Provision Homemedia
  gather_facts: true
  remote_user: "{{user}}"
  become: yes
  hosts: localhost

  vars_files:
    - vars/cloud.yaml

  tasks:
  - name: Dump some facts
    debug: "msg='OS family/distribution: {{ansible_os_family}}/{{ansible_distribution}}'"

  - include_role:
      name: holms.fqdn

  - name: Install utility packages common to all hosts
    apt:
      name:
      - docker
      - docker-compose
      - python-apt
      - sudo
      - tzdata
      state: present
      autoclean: yes

  - name: Creates directory
    file:
      path: "/media/my_user/storage/homemedia"
      state: directory
      owner: "{{user}}"
      group: "{{user}}"
      recurse: yes
      mode: "u=rwX,g=rX,o=rX"
      
  - name: Set Acme Permissions
    file:
      path: "/media/my_user/storage/homemedia/config/traefik/acme.json"
      mode: "0600"
      owner: "{{user}}"
      group: "{{user}}"
      state: file

  - name: Start docker
    service:
      name: docker
      enabled: yes
      state: started

  - name: Add Vagrant to Docker group
    user:
      name: "{{user}}"
      groups: docker
      append: yes

  - name: Start docker services
    command: /usr/bin/docker-compose up -d
    args:
      chdir: "/home/{{user}}/homemedia-docker"
