version: '3.4'
services:
  pia:
    image: qmcgaw/private-internet-access:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - 8113:8113
    environment:
      - USER=${PIA_USER}
      - PASSWORD=${PIA_PASS}
      - PROTOCOL=udp
      - ENCRYPTION=strong
      - REGION=${PIA_REGION}
      - EXTRA_SUBNETS=192.168.1.0/24
      - NONROOT=
    labels:
      - 'traefik.backend=pia'
      - 'traefik.local.frontend.rule=Host:qbit.localhost'
      - 'traefik.port=8113'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:qbit.${DOMAIN}'
      - 'traefik.https.frontend.entrypoints=https'
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use basic auth instead of organizr auth

  hydra2:
    image: linuxserver/hydra2:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/hydra2:/config
      - ${ROOT}/usenet:/data/usenet
    ports:
      - 5076:5076
    restart: unless-stopped
    labels:
      - 'traefik.backend=hydra'
      - 'traefik.local.frontend.rule=Host:hydra2.localhost'
      - 'traefik.port=5076'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:hydra2.${DOMAIN}'
      - 'traefik.https.frontend.entrypoints=https'
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use basic auth instead of organizr auth

  ombi:
    image: linuxserver/ombi:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    labels:
      - 'traefik.backend=ombi'
      - 'traefik.local.frontend.rule=Host:ombi.localhost'
      - 'traefik.port=3579'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:ombi.${DOMAIN}'
      - 'traefik.https.frontend.entryPoints=https'

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    network_mode: service:pia
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      - WEBUI_PORT=8113
    volumes:
      - ${ROOT}/config/qbittorrent:/config
      - ${ROOT}/torrents:/data/torrents
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/torrents/blackhole:/blackhole # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
    labels:
      - 'traefik.backend=jackett'
      - 'traefik.local.frontend.rule=Host:jackett.localhost'
      - 'traefik.port=9117'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:jackett.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  nzbget:
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    ports:
      - 6789:6789
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/usenet:/data/usenet # download folder
      - ${ROOT}/config/nzbget:/config # config files
    labels:
      - 'traefik.backend=nzbget'
      - 'traefik.local.frontend.rule=Host:nzbget.localhost'
      - 'traefik.port=6789'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:nzbget.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  sonarr:
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}:/data
      - ${ROOT}/config/sonarr:/config # config files
    labels:
      - 'traefik.backend=sonarr'
      - 'traefik.local.frontend.rule=Host:sonarr.localhost'
      - 'traefik.port=8989'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:sonarr.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}:/data
      - ${ROOT}/config/radarr:/config # config files
    labels:
      - 'traefik.backend=radarr'
      - 'traefik.local.frontend.rule=Host:radarr.localhost'
      - 'traefik.port=7878'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:radarr.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  bazarr:
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${ROOT}/library:/library
    labels:
      - 'traefik.backend=bazarr'
      - 'traefik.local.frontend.rule=Host:bazarr.localhost'
      - 'traefik.port=6767'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:bazarr.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  organizr:
    image: organizrtools/organizr-v2:latest
    restart: unless-stopped
    expose:
      - '80'
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
    volumes:
      - ${ROOT}/config/organizr:/config
    labels:
      - 'traefik.backend=organizr'
      - 'traefik.local.frontend.rule=Host:organizr.localhost'
      - 'traefik.port=80'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:organizr.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access

  plex-server:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host # access on port 32400
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/library:/data # media library

  tautulli:
    image: linuxserver/tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/tautulli:/config
      - ${ROOT}/logs/tautulli:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - 'traefik.backend=tautulli'
      - 'traefik.local.frontend.rule=Host:tautulli.localhost'
      - 'traefik.port=8181'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:tautulli.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'

  traefik:
    image: traefik:latest
    restart: always
    command:
      --logLevel=info --entryPoints="Name:http Address::80" --defaultEntryPoints=https,http \
      --docker --docker.domain=${DOMAIN} --docker.endpoint="unix:///var/run/docker.sock" \
      --docker.watch=true --docker.exposedbydefault=false \
      --api \
      --entryPoints="Name:https Address::443 TLS" \
      --acme=true --acme.entrypoint=https --acme.httpchallenge --acme.httpchallenge.entrypoint=http \
      --acme.domains=${DOMAIN} --acme.email=${EMAIL} --acme.storage=acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT}/config/traefik/acme.json:/acme.json
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.local.frontend.rule=Host:traefik.localhost'
      - 'traefik.port=8080'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:traefik.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoint=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth
