version: '3.4'
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112
    command: '-r 192.168.1.0/24' # route local network traffic
    labels:
      - 'traefik.backend=vpn'
      - 'traefik.local.frontend.rule=Host:deluge.localhost'
      - 'traefik.port=8112'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:deluge.${DOMAIN}'
      - 'traefik.https.frontend.entryPoints=https'
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
    labels:
      - 'traefik.backend=jackett'
      - 'traefik.local.frontend.rule=Host:jackett.localhost'
      - 'traefik.port=9117'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:jackett.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    ports:
      - 6789:6789
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # download folder
      - ${ROOT}/config/nzbget:/config # config files
    labels:
      - 'traefik.backend=nzbget'
      - 'traefik.local.frontend.rule=Host:nzbget.localhost'
      - 'traefik.port=6789'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:nzbget.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    labels:
      - 'traefik.backend=sonarr'
      - 'traefik.local.frontend.rule=Host:sonarr.localhost'
      - 'traefik.port=8989'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:sonarr.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
    labels:
      - 'traefik.backend=radarr'
      - 'traefik.local.frontend.rule=Host:radarr.localhost'
      - 'traefik.port=7878'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:radarr.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${ROOT}/complete/movies:/movies
      - ${ROOT}/complete/tv:/tv
    labels:
      - 'traefik.backend=bazarr'
      - 'traefik.local.frontend.rule=Host:bazarr.localhost'
      - 'traefik.port=6767'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:bazarr.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth

  organizr:
    container_name: organizr
    image: organizrtools/organizr-v2:latest
    restart: unless-stopped
    expose:
      - '80'
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
    volumes:
      - ${ROOT}/config/organizr:/config
    labels:
      - 'traefik.backend=organizr'
      - 'traefik.local.frontend.rule=Host:organizr.localhost'
      - 'traefik.port=80'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:organizr.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoints=https' # delete for no remote access

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host # access on port 32400
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library

  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    command:
      --logLevel=info --entryPoints="Name:http Address::80" --defaultEntryPoints=https,http \
      --docker --docker.domain=${DOMAIN} --docker.endpoint="unix:///var/run/docker.sock" \
      --docker.watch=true --docker.exposedbydefault=false \
      --api \
      --entryPoints="Name:https Address::443 TLS" \
      --acme=true --acme.entrypoint=https --acme.httpchallenge --acme.httpchallenge.entrypoint=http \
      --acme.domains=${DOMAIN} --acme.email=${EMAIL} --acme.storage=acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT}/config/traefik/acme.json:/acme.json
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.local.frontend.rule=Host:traefik.localhost'
      - 'traefik.port=8080'
      - 'traefik.enable=true'
      - 'traefik.https.frontend.rule=Host:traefik.${DOMAIN}' # delete for no remote access
      - 'traefik.https.frontend.entryPoint=https' # delete for no remote access
      - 'traefik.https.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1'
      # - 'traefik.https.frontend.auth.basic.users=${USERNAME}:${PASSWORD}' # uncomment this line and comment line above to use Basic Auth instead of Organizr auth
