version: '3.4'
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    expose:
      - '8112'
    command: '-r 192.168.1.0/24' # route local network traffic
    labels:
      - 'traefik.backend=vpn'
      - 'traefik.local.frontend.rule=Host:deluge.localhost'
      - 'traefik.port=8112'
      - 'traefik.enable=true'

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    expose:
      - '9117'
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
    labels:
      - 'traefik.backend=jackett'
      - 'traefik.local.frontend.rule=Host:jackett.localhost'
      - 'traefik.port=9117'
      - 'traefik.enable=true'

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    expose:
      - '6789'
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # download folder
      - ${ROOT}/config/nzbget:/config # config files
    labels:
      - 'traefik.backend=nzbget'
      - 'traefik.local.frontend.rule=Host:nzbget.localhost'
      - 'traefik.port=6789'
      - 'traefik.enable=true'

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    expose:
      - '8989'
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    labels:
      - 'traefik.backend=sonarr'
      - 'traefik.local.frontend.rule=Host:sonarr.localhost'
      - 'traefik.port=8989'
      - 'traefik.enable=true'

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    expose:
      - '7878'
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
    labels:
      - 'traefik.backend=radarr'
      - 'traefik.local.frontend.rule=Host:radarr.localhost'
      - 'traefik.port=7878'
      - 'traefik.enable=true'

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    expose:
      - '6767'
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${ROOT}/complete/movies:/movies
      - ${ROOT}/complete/tv:/tv
    labels:
      - 'traefik.backend=bazarr'
      - 'traefik.local.frontend.rule=Host:bazarr.localhost'
      - 'traefik.port=6767'
      - 'traefik.enable=true'

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library

  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    command:
      --logLevel=info --entryPoints="Name:http Address::80" --defaultEntryPoints=https,http \
      --docker --docker.endpoint="unix:///var/run/docker.sock" \
      --docker.watch=true --docker.exposedbydefault=false \
      --api
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT}/config/traefik/acme.json:/acme.json
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.local.frontend.rule=Host:traefik.localhost'
      - 'traefik.port=8080'
      - 'traefik.enable=true'
